services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP (optional)

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # OTLP/Jaeger gRPC
      - "6831:6831/udp"
      - "6832:6832/udp"

  app:
    build: .
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_ENVIRONMENT=Development
      - OTLP__Endpoint=http://otel-collector:4317
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - jaeger